UPDATE company SET favicon_url = '/static/favicons/bandcamp.png'    WHERE name = 'Bandcamp';
UPDATE company SET favicon_url = '/static/favicons/beatport.png'    WHERE name = 'Beatport';
UPDATE company SET favicon_url = '/static/favicons/cloudflare.png'  WHERE name = 'Cloudflare';
UPDATE company SET favicon_url = '/static/favicons/denon-dj.png'    WHERE name = 'Denon DJ';
UPDATE company SET favicon_url = '/static/favicons/garmin.png'      WHERE name = 'Garmin';
UPDATE company SET favicon_url = '/static/favicons/mixcloud.ico'    WHERE name = 'Mixcloud';
UPDATE company SET favicon_url = '/static/favicons/nvidia.ico'      WHERE name = 'Nvidia';
UPDATE company SET favicon_url = '/static/favicons/oura.png'        WHERE name = 'Oura';
UPDATE company SET favicon_url = '/static/favicons/oxide.svg'       WHERE name = 'Oxide Computer Company';
UPDATE company SET favicon_url = '/static/favicons/pioneer-dj.ico'  WHERE name = 'Pioneer DJ (JP)';
UPDATE company SET favicon_url = '/static/favicons/pioneer-dj.ico'  WHERE name = 'Pioneer DJ (US)';
UPDATE company SET favicon_url = '/static/favicons/plaid.png'       WHERE name = 'Plaid';
UPDATE company SET favicon_url = '/static/favicons/proton.ico'      WHERE name = 'Proton';
UPDATE company SET favicon_url = '/static/favicons/rivian.ico'      WHERE name = 'Rivian';
UPDATE company SET favicon_url = '/static/favicons/samsara.png'     WHERE name = 'Samsara';
UPDATE company SET favicon_url = '/static/favicons/shure.ico'       WHERE name = 'Shure';
UPDATE company SET favicon_url = '/static/favicons/sofi.ico'        WHERE name = 'SoFi';
UPDATE company SET favicon_url = '/static/favicons/soundcloud.ico'  WHERE name = 'SoundCloud';
UPDATE company SET favicon_url = '/static/favicons/strava.ico'      WHERE name = 'Strava';
UPDATE company SET favicon_url = '/static/favicons/stripe.ico'      WHERE name = 'Stripe';
UPDATE company SET favicon_url = '/static/favicons/tailscale.png'   WHERE name = 'Tailscale';
UPDATE company SET favicon_url = '/static/favicons/whoop.ico'       WHERE name = 'Whoop';
